### ISSUE TITLE
Create Cached Buildpack Releases

### ISSUE THREAD

**Issue by johnlonganecker** [cloudfoundry-incubator/hwc-buildpack#8]
It would make our lives a little bit nicer if you could add cached version of the buildpack like you did in previous releases. Thanks!

**Comment by sclevine** [comment]
Hi @johnlonganecker,

[CFF policy](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/SN5AW5SUAMHDQAAPU45AURTBWEXWU2MN/) prevents us from providing cached buildpacks on Github. Apologies for the inconvenience.
